server00 ansible_host=172.16.10.20 ansible_user=vagrant ansible_ssh_private_key_file=./.vagrant/machines/server00/virtualbox/private_key
server01 ansible_host=172.16.10.21 ansible_user=vagrant ansible_ssh_private_key_file=./.vagrant/machines/server01/virtualbox/private_key
server02 ansible_host=172.16.10.22 ansible_user=vagrant ansible_ssh_private_key_file=./.vagrant/machines/server02/virtualbox/private_key

[monitoring]
server00

[targets]
server01
server02
