#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker_setup
- name: Installing required packages
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: true

- name: Adding Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Adding Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Installing Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Adding vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: true

- name: Exposing Docker metrics
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/
  notify:
    - restart docker

- name: "Creating {{ path }} directory"
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory

- name: Copying docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ path }}/docker-compose.yml"

- name: Copying prometheus.yml
  ansible.builtin.copy:
    src: prometheus.yml
    dest: "{{ path }}"
  when: enable_prometheus_installation

- name: Running docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ path }}"
