---
- name: Docker Compose setup
  hosts: targets
  vars:
    path: "/opt/docker/prometheus"
  tasks:
    - name: Copy docker-compose.yml
      ansible.builtin.copy:
        src: files/targets/
        dest: "{{ path }}"

    - name: Run docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ path }}"

- name: Docker Compose setup
  hosts: prometheus
  vars:
    path: "/opt/docker/prometheus"
  tasks:
    - name: Copy docker-compose.yml and prometheus.yml
      ansible.builtin.copy:
        src: files/prometheus/
        dest: "{{ path }}"

    - name: Run docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ path }}"
